custom_book_user:
    resource: "@CustomBookBundle/Resources/config/routing/user.yml"
    prefix:   /user

custom_book_book:
    resource: "@CustomBookBundle/Resources/config/routing/book.yml"
    prefix:   /book

custom_book_homepage:
    path:     /hello
    defaults: { _controller: CustomBookBundle:Default:index }


login:
  path: /login
  defaults: { _controller: CustomBookBundle:Security:login }

login_check:
  path: /login_check

logout:
  pattern: /logout